### PR TITLE
FIX: PSR-2 codebase. Formatting via phpcbf

### LINKED ISSUE #43: Update codebase to be PSR-2 compliant

### PR DESCRIPTION
**Pull request by NightJar**
Updates the code base to be PSR-2 compliant

- [x] Depends on #42 

Closes #43

### CODE REVIEW

**Comment by robbieaverill** [comment]
Needs a rebase now

**Comment by robbieaverill** [comment]
Merge on green

**Comment by robbieaverill** [comment]
Ok so we should _probably_ remove this logic and use the ORM:

https://github.com/creative-commoners/silverstripe-versionfeed/blob/549d230adc73931a4bc52ed12e8ac17e54377998/src/VersionFeedController.php#L106-L112

But for now let's update it to `_Versions` or whatever the SS4 table name is so the builds will pass.

**Comment by NightJar** [comment]
Yeah, there's a couple of blocks like that - the module is more heavily tied to SiteTree than I had first thought.

**Comment by robbieaverill** [comment]
Builds aren't quite there yet, but as this is a PSR-2 linting pull request I think we should merge it anyway

**Pull request merged**
