### PR TITLE
Make it installable with vendor folder usage

### PR DESCRIPTION
**Pull request by NightJar**
If we do this one now, maybe git won't forget the history of the src files in future when we merge the rest of the changes.

### CODE REVIEW

**Comment by robbieaverill** [comment]
We may as well do all the renaming at once eg caching > Caching and no underscores in controller filenames. The builds will break but that's ok

**Comment by NightJar** [comment]
@robbieaverill I was hoping to avoid the loss of a file's history issue in git which seems to manifest where we've both moved the files and made changes. Thus if we merge this first then make the alterations we're only doing one change at a time, hopefully it makes it easier for the history to see that the new file and the old file are the same, and not lose all that history.

Could end up being a futile test, but at least we could say we tried.

**Comment by robbieaverill** [comment]
Yeah, that's a good idea. A rename is still only one change though, so you may as well just change it once.

**Comment by NightJar** [comment]
Yeh, but by all accounts around the interewebs it's the fact that oldFile & newFile contain the same content that counts. But now I've just realised you mean the filenames, not the classnames, so that's fine. brb.

**Comment by NightJar** [comment]
Cool, I think that's it for the renaming.

**Pull request merged**
